# Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
- Addition of 2 in all the element
- Multiply 3 with all the elements
- Divide every element by 2

In [13]:
import numpy as np
a = np.array([0, 1, 2, 3, 4])
a = a + 2
print(a)
a = a * 3
print(a)
a = a / 2
print(a)

[2 3 4 5 6]
[ 6  9 12 15 18]
[3.  4.5 6.  7.5 9. ]


# Q.2 Questions on Basic NumPy Array:
- Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
- Find the most frequent value and their indice(s) in the following arrays:
  *  x = np.array([1,2,3,4,5,1,2,1,1,1])
  *  y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [24]:
a = np.array([1, 2, 3, 6, 4, 5])
a = a[::-1]
print(a)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
m_freq = np.bincount(x).argmax()
indices = np.where(x == m_freq)[0]
print("The most frequent in x is", m_freq, "at indices", indices)
y = ([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
m_freq = np.bincount(y).argmax()
indices = np.where(y == m_freq)[0]
print("The most frequent in y is", m_freq, "at indices", indices)

[5 4 6 3 2 1]
The most frequent in x is 1 at indices [0 5 7 8 9]
The most frequent in y is 1 at indices [0 1 2]


# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
- Access 1st row, 2nd column
- Access 3rd row, 1st column:

In [36]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Value at 1st row, 2nd column", arr[0, 1])
print("Value at 3rd row, 1st column",arr[2, 0])

Value at 1st row, 2nd column 20
Value at 3rd row, 1st column 70


# Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [3]:
import numpy as np
Janhvi = np.linspace(10, 100, 25)
print("Dimensions of array:", Janhvi.ndim)
print("Shape of array:", Janhvi.shape)
print("Total Elements of array:", Janhvi.size)
print("Data Type of array:", Janhvi.dtype)
print("Total Bytes consumed by array:", Janhvi.nbytes)
transpose1 = Janhvi.reshape(25, 1)
print("Transpose using reshape", transpose1)
transpose2 = Janhvi.T
print("Transpose using T attribute", transpose2)

Dimensions of array: 1
Shape of array: (25,)
Total Elements of array: 25
Data Type of array: float64
Total Bytes consumed by array: 200
Transpose using reshape [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


# Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [17]:
ucs420_Janhvi = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
mean = np.mean(ucs420_Janhvi)
print("Mean:", mean)
median = np.median(ucs420_Janhvi)
print("Median:", median)
max = np.max(ucs420_Janhvi)
print("Max:", max)
min = np.min(ucs420_Janhvi)
print("Min:", min)
unique = np.unique(ucs420_Janhvi)
print("Unique:", unique)
reshaped_ucs420_Janhvi = ucs420_Janhvi.reshape(4, 3)
print("Reshaped Array:", reshaped_ucs420_Janhvi)
resized_ucs420_Janhvi = np.resize(ucs420_Janhvi, (2, 3))
print("Resized Array:", resized_ucs420_Janhvi)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array: [[10 20 30]
 [40 50 60]]
